### ISSUE TITLE
希望可以自定义CSDN文章container宽度

### ISSUE THREAD

**Issue by smallx** [SublimeCT/greasy_monkey_scripts#4]
目前的CSDN文章的container宽度个人觉得有点宽, 希望可以自定义宽度, 感谢.

**Comment by SublimeCT** [comment]
```css
@media (max-width: 1380px) and (min-width: 1320px) {
    .nodata .container {
        width:1208px
    }

    .nodata .container main {
        width: 900px
    }
}

@media screen and (max-width: 1320px) {
    .nodata .container {
        width:1068px
    }

    .nodata .container main {
        width: 760px
    }
}

@media screen and (min-width: 1380px) {
    .nodata .container {
        width:1318px
    }

    .nodata .container main {
        width: 1010px
    }
}

@media (min-width: 1550px) and (max-width:1700px) {
    .nodata .container {
        width:1128px
    }

    .nodata .container main {
        width: 820px
    }
}

@media screen and (min-width: 1700px) {
    .nodata .container {
        width:1318px
    }

    .nodata .container main {
        width: 1010px
    }
}
```

**如上 `csdn` 源码中的宽度是 `media query` 的**, 针对不同的页面宽度设置了不同的宽度; 在脚本中文章的宽度也与 `.container` 一致

固定宽度也没啥问题, 只是调整窗口大小后依然是设置的宽度, 所以如果要设置文章宽度, 有以下两种可选方案:

- 为每个尺寸单独设置宽度(px)
- 为每个尺寸设置基于 `.container` 宽度的百分比宽度, *比如宽度设置为 `.container` 的 `80%`*

这个功能我会考虑加上的
